<a href="https://colab.research.google.com/github/BrunoTohoru/exercicios_java_Repeticao/blob/main/00_tenserflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Aqui veremos alguns dos fundamentos e conseitos do tensor usando TenserFlow

Mais especificamente, vamos ter:
* Introdução de Tensors
* Coletar informações dos Tensors
* Manipular Tensors
* Tensors & Numpy
* Usar @tf.function (um jeito de agilizar as funcções regulares de Python)
* Usar GPUs com TenserFlow (ou TPUs)
* Exercicios para fixação

#Introdução de Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [3]:
# Criando Tensors com tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Checando o número de dimensões de um Tensor (ndim refere-se ao número de dimensões)
scalar.ndim

0

In [5]:
# Criando um vetor
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Checando a dimensão do vetor
vector.ndim

1

In [7]:
# Criando a matriz (tem mais de uma dimensão)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Criando uma nova matriz
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16) # especificando o tipo de dado com o comando dtype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
# Qual o número de dimensões que aparecerá usando o ndim?
another_matrix.ndim

2

In [11]:
# Vamos criar um Tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

O que crimaos até agora:
* Scalar: Um elemento apenas
* Vector: Um vetor unidimencional de elementos
* Matrix: Uma matriz bidimensional de elementos
* Tensor: Uma matriz n-dimensional de elementos

### Criando Tensors com tf.Variable

In [13]:
# Criando o mesmo tensor  com tf.Variable() como a de cima
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Vamos tentar mudar um dos elementos do Tensor modificável
#changeable_tensor[0] = 7 (vai dar erro)
#changeable_tensor

In [15]:
# E se tentarmos com .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Criando aleatoriamento Tensors



In [16]:
# Criando dois Tensors aleatorios (mas iguais) 
random_1 = tf.random.Generator.from_seed(42) # usasse seed para reprodução
random_1 = random_1.normal(shape = (3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))

# São iguais?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Como misturar as odens dos elementos do Tensor

In [17]:
# Misturando um Tensor
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim

# Misturando nosso Tensor não-misturado
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [18]:
# Misturando nosso Tensor não-misturado
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

###⚓**Exercicio:** Ler documentoação sobre random seed generation no TensorFlow:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed

e faça mais 5 random tensors e misture eles

In [19]:
# Exercicio 01
exec_01 = tf.constant([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[10, 11, 12],
                        [13, 14, 15],
                        [16, 17, 18]],
                       [[19, 20, 21],
                        [22, 23, 24],
                        [25, 26, 27]]])
tf.random.set_seed(42) # seed global
tf.random.shuffle(exec_01, seed = 42) # seed operacional 

# com seed global e operacional, não tem mudanças no shuffle

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]], dtype=int32)>

In [20]:
# Exercicio 02
exec_02 = tf.constant([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[10, 11, 12],
                        [13, 14, 15],
                        [16, 17, 18]],
                       [[19, 20, 21],
                        [22, 23, 24],
                        [25, 26, 27]]])
tf.random.shuffle(exec_02)

# sem seed global e operacional (seed global é default), tem mudanças no shuffle

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]], dtype=int32)>

In [21]:
# Exercicio 03
exec_03 = tf.constant([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[10, 11, 12],
                        [13, 14, 15],
                        [16, 17, 18]],
                       [[19, 20, 21],
                        [22, 23, 24],
                        [25, 26, 27]]])
tf.random.shuffle(exec_03, seed = 12)

# apenas seed operacional, tem mudanças no shuffle

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]], dtype=int32)>

In [22]:
# Exercicio 04
exec_04 = tf.constant([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[10, 11, 12],
                        [13, 14, 15],
                        [16, 17, 18]],
                       [[19, 20, 21],
                        [22, 23, 24],
                        [25, 26, 27]]])
tf.random.set_seed(60)
tf.random.shuffle(exec_04)

# apenas seed global, porém só há mudanças caso mude o parâmetro do seed

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [23]:
# Exercicio 05
exec_05 = tf.constant([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[10, 11, 12],
                        [13, 14, 15],
                        [16, 17, 18]],
                       [[19, 20, 21],
                        [22, 23, 24],
                        [25, 26, 27]]])
tf.random.set_seed(None)
tf.random.shuffle(exec_05, seed = None)

# Mesmo com ambos seed com None, há mudanças no Tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]], dtype=int32)>

### Outros jeitos de criar Tensors

In [24]:
# Cria um Tensor de apenas 1's
tf.ones([10, 7]) 

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [25]:
# Cria um Tensor de apenas 0's
tf.zeros(shape = (10, 7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Transformar vetores NumPy em Tensors

A principal diferença entre vetores NumPy e TensorFlow Tensors é que Tensors podem rodar em GPU (mais rapidos para computação numérica).

In [26]:
# Também podemos transformar vetores Numpy em Tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# Y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [27]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [28]:
# Exercicio, criando NumPy arrays e transforamando eles em Tensors
import numpy as np
import tensorflow as tf
#criação de um vetor NumPy
exerc_06 = np.arange(1, 21, dtype=np.int32)
exerc_06
#transformando em Tensor
exerc_06_tensor1 = tf.constant(exerc_06, shape=(4,5))
exerc_06_tensor2 = tf.constant(exerc_06, shape=(2,2,5))
exerc_06_tensor1,exerc_06_tensor2

(<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 5), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],
 
        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]], dtype=int32)>)

### Colhendo informações dos Tensors
Quando utilizando um Tensor, provavelmente precisará prestar atenção nos atributos abaixo:
* Shape (tensor.shape)
* Rank (tensor.ndim)
* Axis or dimensão (tensor[0], tensor[:, 1]...)
* Tamanho (tf.size(tensor))

In [29]:
# Criando um rank 4 Tensor (4 dimensões)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [31]:
# Pegando varios atributos do Tensor
print("Tipo de dados de todos os elementos:", rank_4_tensor.dtype)
print("Numero de dimensões (rank):", rank_4_tensor.ndim)
print("Shape do Tensor:", rank_4_tensor.shape)
print("Elementos pelo eixo 0:", rank_4_tensor.shape[0])
print("Elementos pelo último eixo:", rank_4_tensor.shape[-1])
print("Total de numeros de elementos no Tensor:", tf.size(rank_4_tensor).numpy())

Tipo de dados de todos os elementos: <dtype: 'float32'>
Numero de dimensões (rank): 4
Shape do Tensor: (2, 3, 4, 5)
Elementos pelo eixo 0: 2
Elementos pelo último eixo: 5
Total de numeros de elementos no Tensor: 120


### Indexando um Tensor
Tensors podem ser indexados como uma lista de Python

In [32]:
# Pegando os 2 primeiros elementos de cada dimensão
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [33]:
# Pegar o primeiro elemento de cada dimensão, exceto da ultima dimensão
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [34]:
rank_4_tensor[:1, :1, :, :1]


<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [35]:
rank_4_tensor[:1, :, :1, :1]


<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [36]:
rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [37]:
# Criando um Tensor rank 2 (2 dimensões)
rank_2_tensor = tf.constant([[1, 2, 3, 4],
                             [5 ,6 ,7, 8]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 4]), 2)

In [38]:
# Pegando o ultimo elemento de cada dimensão do Tensor rank 2
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 8], dtype=int32)>

In [39]:
# Adicionando uma dimensão extra em nosso Tensor rank 2
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 4, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]], dtype=int32)>

In [40]:
# Alternativa para tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" significa expandir o última dimensão

<tf.Tensor: shape=(2, 4, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]], dtype=int32)>

In [41]:
tf.expand_dims(rank_2_tensor, axis=0) # expandindo a dimensão 0 você adiciona uma dimensão no início do shape

<tf.Tensor: shape=(1, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]], dtype=int32)>

### Manipulando Tensores (tensores operacionais)
**Manipulação com operadores e funções**

Operadores -> +, -, *, /

Funções -> tf.math. ... add, substract, multiply, divide

In [42]:
# Você pode adicionar valores para os tensores usando operadores aditivos
tensor = tf.constant([[10, 7],[3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [43]:
# O tensor original não é alterado
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [44]:
# Multiplicação também funciona
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [45]:
# Podemos usar a função TensorFlow built-in também
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Multiplicação de Matrizes**

Em Machine Learnig, multiplicação de matrizes são as operações mais comuns em Tensores

**tf.matmul ou tf.linalg.matmul**

linalg - algebra linear

matmul - multiplicação de matrizes

Existem regras para realizar a multiplicação de matrizes:
1. As dimensões internas devem ser iguais
2. A matriz resultante deve ter o mesmo shape das dimensões externas

In [46]:
# Multiplicação de matrizes em TensorFlow
print(tensor)
tf.matmul(tensor, tensor) # é diferente de (tensor * tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [47]:
# Multiplicação de matrizes com operador Python "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [48]:
# Criando Tensors (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Criando outro (2, 3)
Y = tf.constant([[7, 8, 9],
                 [10, 11, 12]])
# Criando outro (3, 2)
Z = tf.constant([[7 ,8],
                 [9 ,10],
                 [11, 12]])
X, Y, Z

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [49]:
# Multiplicando X e Y de (3,2) e (2, 3) shape
X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [50]:
# Vamos mudar o shape do Z
tf.reshape(Z, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [51]:
# Tentando multiplicar X pelo reshape Z
X @ tf.reshape(Z, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [52]:
tf.matmul(X, tf.reshape(Z, shape = (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [53]:
# Podemos traspor
X, tf.transpose(X), tf.reshape(X, shape = (2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [54]:
# Multiplicar matrizes com transpose é correto, com reshape não lhe da os valores ideais
tf.matmul(tf.transpose(X), Z)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

** Multiplicação de matrizes / DOT PRODUCT **

Você consegue multiplicar utilizando

* tf.matmul() ou tf.linalg.matmul()

* tf.tensordot()

In [55]:
# Realizar a multiplicação transpondo X ou Y
tf.matmul(X, tf.transpose(Z))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

### Mudando o tipo de dado do Tensor

In [56]:
# Criando um novo Tensor 
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [57]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [58]:
# Mudar de float32 para float16 (reduz precisão e aumenta velocidade)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [59]:
# Mudar de int32 para int16
E = tf.cast(C, dtype=tf.int16)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=int16, numpy=array([ 7, 10], dtype=int16)>,
 tf.int16)

### Agregando Tensors

Agregando Tensors = resumo de vários valores em uma quantidade menor de dados que os represente

In [60]:
# Pegando os valores absolutos
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [61]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Vamos ver algumas formas de agregação:
* Pegar o minimo
* Pegar o maximo
* Pegar a média
* Pegar a somatória

In [62]:
# Criando um Tensor pro exercicio
exerc_07_numpy = np.arange(1, 25, dtype = np.int16)
exerc_07 = tf.constant(exerc_07_numpy, shape = (2, 3, 4))
exerc_07

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [63]:
# Exercicio 07.1 - pegando minimo
tf.reduce_min(exerc_07)

<tf.Tensor: shape=(), dtype=int16, numpy=1>

In [64]:
# Exercicio 07.2 - pegando máximo
tf.reduce_max(exerc_07)

<tf.Tensor: shape=(), dtype=int16, numpy=24>

In [65]:
# Exercicio 07.3 - pegando máximo
tf.reduce_mean(exerc_07)

<tf.Tensor: shape=(), dtype=int16, numpy=12>

In [66]:
# Exercicio 07.4 - pegando máximo
tf.reduce_sum(exerc_07)

<tf.Tensor: shape=(), dtype=int16, numpy=300>

In [67]:
# Criando um Tensor aleatório com valores de 0 a 100 de tamanho 50
E = tf.constant(np.random.randint(0,100, size=50)) # CRIANDO UM VETOR ALEATÓRIOOOOOO
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([87, 75, 34, 63, 83, 50, 27,  7, 23, 38, 15, 18, 11, 86, 31, 31, 45,
       51, 42, 43, 29, 29, 47, 31, 55,  5, 27,  7, 19, 26, 22, 44, 22, 23,
       44, 27, 81, 14, 18, 94, 11, 20, 21, 90, 23,  7, 35,  0, 55, 85])>

In [68]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [69]:
Emin = tf.reduce_min(E)
Emax = tf.reduce_max(E)
Emean = tf.reduce_mean(E)
Esum = tf.reduce_sum(E)
Emin, Emax, Emean, Esum

(<tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=94>,
 <tf.Tensor: shape=(), dtype=int64, numpy=37>,
 <tf.Tensor: shape=(), dtype=int64, numpy=1871>)

⚓**Exercicio:** Encontre a variância e o desvio padrão da Tensor E

In [70]:
# Exercício 08.1 - encontrando a variancia do Tensor E
Evar = tf.cast(E, dtype = tf.float16)
tf.math.reduce_variance(Evar)

<tf.Tensor: shape=(), dtype=float16, numpy=630.5>

In [71]:
# Exercício 08.2 - encontrando o desvio padrão do Tensor E
Estd = tf.cast(E, dtype = tf.float16)
tf.math.reduce_std(Estd)

<tf.Tensor: shape=(), dtype=float16, numpy=25.11>

Também pode ser usado:

import tensorflow_probability as std

std.stats.variance(E)

### Encontrando o máximo e mínimo posicional


In [72]:
# Criando um novvo Tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [73]:
# Encontrando a posição do maior valor do Tensor F
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [74]:
# Pegando o valor pela posição (index ou índice)
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [75]:
# Pelo compararmos os valores máximos pelos dois metodos teremos:
F[tf.argmax(F)] == tf.reduce_max(F) # TRUE / VERDADEIRO

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [76]:
# Encontrando a posição do menor valor do Tensor F
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [77]:
# Pegando o valor pela posição (index ou índice)
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Diminuindo o Tensor (remover todas as dimensões unitárias)


In [78]:
# Criando um Tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [79]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [80]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-Hot Encoding Tensors

Uma forma de codificação numérica para melhor entendimento das linhas neurais

In [81]:
# Criando uma lista de índices
some_list = [0, 1, 2, 3] # poderia ser red, green, blue, purple

# One hot encode nosssa lista
tf.one_hot(some_list, tf.size(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [82]:
# Especificando os valores customizáveis para one hot encoding
tf.one_hot(some_list, tf.size(some_list), on_value="x", off_value="y")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'x', b'y', b'y', b'y'],
       [b'y', b'x', b'y', b'y'],
       [b'y', b'y', b'x', b'y'],
       [b'y', b'y', b'y', b'x']], dtype=object)>

### Squaring, log, square root

In [83]:
# Criando um novo Tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [84]:
# Square / ao quadrado
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [85]:
# Square root / raiz ao quadrado
tf.sqrt(tf.cast(H, dtype = tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [86]:
# Log
tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

### Pow, Subtract, Add

In [87]:
# Criando um Tensor exemplo
tf.random.set_seed(42)
exemplo1 = tf.random.uniform([50])
exemplo2 = tf.random.uniform([50])
exemplo1, exemplo2

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.71489

In [88]:
# usando Pow
tf.pow(exemplo1, exemplo2) # Calcula a potência de um valor para outro.

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7549597 , 0.67257583, 0.37918064, 0.8241647 , 0.08377174,
       0.71311104, 0.752074  , 0.9028026 , 0.5951647 , 0.44016293,
       0.73634326, 0.79706305, 0.78571147, 0.72496253, 0.6729395 ,
       0.9116491 , 0.20536107, 0.89294875, 0.8179324 , 0.23390172,
       0.9573832 , 0.9286973 , 0.27718973, 0.6922846 , 0.6829509 ,
       0.5222962 , 0.73297316, 0.27841702, 0.8757698 , 0.48156464,
       0.9992725 , 0.48871708, 0.88700837, 0.64401275, 0.5854927 ,
       0.24847943, 0.93376034, 0.8867704 , 0.53048503, 0.8516743 ,
       0.5618703 , 0.8486884 , 0.9945524 , 0.6138928 , 0.8040698 ,
       0.9748371 , 0.7539754 , 0.16852367, 0.86575633, 0.37389448],
      dtype=float32)>

In [89]:
# Usando Subtract
tf.subtract(exemplo1, exemplo2) # Subtrai os Tensors

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([-0.02332914, -0.04347205, -0.5781119 ,  0.21229553, -0.69749355,
       -0.20789587, -0.20663083,  0.12311041, -0.12292993, -0.3239857 ,
        0.04878414,  0.02499259,  0.01356137,  0.01322043, -0.140288  ,
        0.02466571, -0.33021128,  0.34745443,  0.1926924 , -0.7014978 ,
        0.5913838 ,  0.4236548 , -0.4678836 , -0.26501203, -0.2583822 ,
       -0.26013434, -0.00953054, -0.6102369 ,  0.02003932, -0.45096314,
        0.9347553 , -0.2605487 ,  0.23675632, -0.15928006, -0.26541984,
       -0.69281554,  0.4367175 , -0.00463128, -0.23051405,  0.25947285,
       -0.16353261,  0.11549032,  0.80365777, -0.11350083, -0.17166233,
        0.5988898 ,  0.05680382, -0.82238245,  0.26340783, -0.544135  ],
      dtype=float32)>

In [90]:
# Usando Add
tf.add(exemplo1, exemplo2) # Soma os tensors

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([1.3524534 , 0.9254856 , 1.2838769 , 0.71666956, 0.7648144 ,
       1.5772406 , 1.6868657 , 1.6217786 , 0.5755826 , 0.7703794 ,
       0.57199204, 1.419679  , 0.25281298, 1.0829073 , 1.2895056 ,
       1.7747012 , 0.34913862, 0.69500697, 1.0763966 , 1.1001544 ,
       0.8674611 , 0.6680143 , 0.68301463, 1.6184242 , 1.5789348 ,
       0.9340352 , 1.2123659 , 1.0314884 , 1.685435  , 1.3322066 ,
       0.9622998 , 0.7356006 , 1.3868296 , 1.2119589 , 1.2540358 ,
       1.1250725 , 1.2547219 , 1.7483995 , 0.84728646, 1.1141348 ,
       0.6388134 , 1.4479553 , 1.130619  , 0.25090408, 1.7691412 ,
       0.72168446, 1.1174988 , 1.1516163 , 1.2127968 , 1.1852158 ],
      dtype=float32)>

### Tensors e NumPy

TensorFlow interagem muito bem com os vetores NumPy

In [91]:
# Creando um Tensor diretamente do vetor NumPy
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [92]:
# Conveerter o Tensor para NumPy array 1/2
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [93]:
# Converteer Tensor para um Numpy array 2/2
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [94]:
# A funcionalidade nesse processo é de se poder manipulars os elementos em NumPy de modo que não se consegue com TensorFlow
J = tf.constant([3.])
J.numpy()[0]

3.0

In [95]:
# Tipo padrão de cada um é levemente diferente
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.,])

# Verificando os tipos de dados de cada um
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Achando o acesso aos GPUs


In [98]:
# Comando para sabeermos em que tipo de hardware está rodando
tf.config.list_physical_devices() # está rodando em um CPU

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [97]:
tf.config.list_physical_devices("GPU") # '[]' -> indica que não há GPUs

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [99]:
!nvidia-smi # Comando para sabermos que tipo de GPU está rodando

Thu May  4 19:56:00 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P0    26W /  70W |    375MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

❗**Note:** Se temos acesso a um CUDA-enabled GPU, TensorFlow vai automaticamente usar-lo sempre que possível

### Exercício extracurricular


In [15]:
# Exercicio 01 - Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
import tensorflow as tf
import numpy as np
# Com Numpy
scalarnp = np.arange(1) # Scalar ou tensor 0-dim
vetornp = np.arange(10) # Vetor ou tensor 1-dim
matriznp = np.full((3, 3), 9) # Matriz ou tensor 2-dim
tensornp = np.full((2, 3, 4), 24) # Tensor 3-dim
# Com TensorFlow
scalartf = tf.constant([0])
vetortf = tf.constant([1, 2, 3, 4, 5, 6])
matriztf = tf.constant([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])
tensortf = tf.constant([[[1, 2],
                         [3, 4]],
                        
                        [[5, 6],
                         [7, 8]]])
tensortf

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [20]:
# Exercicio 02 - Find the shape, rank and size of the tensors you created in 1.
print(scalartf.shape, scalartf.ndim, tf.size(scalartf)) # Scalar
print(vetortf.shape, vetortf.ndim, tf.size(vetortf)) # Vetor
print(matriztf.shape, matriztf.ndim, tf.size(matriztf)) # Matriz
print(tensortf.shape, tensortf.ndim, tf.size(tensortf)) # Tensor

(1,) 1 tf.Tensor(1, shape=(), dtype=int32)
(6,) 1 tf.Tensor(6, shape=(), dtype=int32)
(3, 3) 2 tf.Tensor(9, shape=(), dtype=int32)
(2, 2, 2) 3 tf.Tensor(8, shape=(), dtype=int32)


In [26]:
# Exercicio 03 - Create two tensors containing random values between 0 and 1 with shape [5, 300].
# Tensor01
tf.random.set_seed(42)
tensor01 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1, dtype=tf.float16)
print(tensor01)
# Tensor02
tensor02 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1, dtype=tf.float16)
print(tensor02)

tf.Tensor(
[[0.0928  0.7275  0.8135  ... 0.1455  0.624   0.02637]
 [0.3408  0.3252  0.03906 ... 0.964   0.3955  0.747  ]
 [0.4727  0.1084  0.2158  ... 0.6436  0.7715  0.535  ]
 [0.577   0.2783  0.3887  ... 0.8467  0.552   0.955  ]
 [0.3613  0.00879 0.718   ... 0.3408  0.4941  0.549  ]], shape=(5, 300), dtype=float16)
tf.Tensor(
[[0.2051  0.8506  0.706   ... 0.4883  0.12305 0.9316 ]
 [0.1445  0.962   0.291   ... 0.8564  0.6377  0.02148]
 [0.3867  0.999   0.927   ... 0.9326  0.5635  0.05957]
 [0.789   0.4307  0.2031  ... 0.8545  0.9434  0.02344]
 [0.6836  0.749   0.7275  ... 0.463   0.9023  0.2568 ]], shape=(5, 300), dtype=float16)


In [34]:
# Exercicio 04 - Multiply the two tensors you created in 3 using matrix multiplication.
tf.matmul(tensor01, tf.transpose(tensor02))

<tf.Tensor: shape=(5, 5), dtype=float16, numpy=
array([[70.2 , 68.75, 68.6 , 67.25, 76.4 ],
       [75.75, 76.06, 74.7 , 76.  , 81.1 ],
       [77.25, 78.06, 71.56, 76.7 , 81.1 ],
       [74.8 , 77.3 , 67.94, 76.  , 78.7 ],
       [76.4 , 76.44, 74.  , 72.4 , 79.4 ]], dtype=float16)>

In [36]:
# Exercicio 05 - Multiply the two tensors you created in 3 using dot product.
tensor01 @ tf.transpose(tensor02)

<tf.Tensor: shape=(5, 5), dtype=float16, numpy=
array([[70.2 , 68.75, 68.6 , 67.25, 76.4 ],
       [75.75, 76.06, 74.7 , 76.  , 81.1 ],
       [77.25, 78.06, 71.56, 76.7 , 81.1 ],
       [74.8 , 77.3 , 67.94, 76.  , 78.7 ],
       [76.4 , 76.44, 74.  , 72.4 , 79.4 ]], dtype=float16)>

In [43]:
# Exercicio 06 - Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tf.random.set_seed(42)
tensor03 = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1, dtype=tf.float16)
print(tensor03)

tf.Tensor(
[[[0.0928   0.7275   0.8135  ]
  [0.04102  0.746    0.836   ]
  [0.042    0.0654   0.0654  ]
  ...
  [0.797    0.4785   0.3428  ]
  [0.2314   0.7773   0.338   ]
  [0.83     0.01172  0.872   ]]

 [[0.4336   0.252    0.9336  ]
  [0.2354   0.667    0.785   ]
  [0.961    0.4707   0.0654  ]
  ...
  [0.3691   0.2148   0.9316  ]
  [0.7334   0.1328   0.4395  ]
  [0.6074   0.6963   0.76    ]]

 [[0.5684   0.579    0.4736  ]
  [0.8477   0.3145   0.6904  ]
  [0.2764   0.9463   0.206   ]
  ...
  [0.6504   0.0947   0.2412  ]
  [0.533    0.11035  0.414   ]
  [0.619    0.165    0.963   ]]

 ...

 [[0.7295   0.752    0.547   ]
  [0.8193   0.0762   0.993   ]
  [0.4824   0.6963   0.2051  ]
  ...
  [0.6035   0.547    0.6465  ]
  [0.508    0.3936   0.6826  ]
  [0.884    0.00586  0.785   ]]

 [[0.9395   0.1826   0.584   ]
  [0.2559   0.836    0.497   ]
  [0.627    0.7393   0.1445  ]
  ...
  [0.8457   0.8975   0.8496  ]
  [0.7705   0.248    0.4014  ]
  [0.1113   0.3516   0.006836]]

 [[0.541    0

In [45]:
# Exercicio 07 - Find the min and max values of the tensor you created in 6 along the first axis.
print(tf.reduce_min(tensor03, axis=0))

tf.Tensor(
[[0.       0.00293  0.003906]
 [0.       0.007812 0.00293 ]
 [0.000977 0.       0.00879 ]
 [0.00586  0.003906 0.      ]
 [0.000977 0.003906 0.001953]
 [0.00293  0.000977 0.00586 ]
 [0.000977 0.004883 0.007812]
 [0.000977 0.007812 0.      ]
 [0.       0.004883 0.00879 ]
 [0.00879  0.009766 0.000977]
 [0.       0.       0.      ]
 [0.003906 0.001953 0.      ]
 [0.001953 0.004883 0.      ]
 [0.00586  0.004883 0.001953]
 [0.       0.000977 0.      ]
 [0.001953 0.007812 0.000977]
 [0.001953 0.009766 0.00293 ]
 [0.01172  0.004883 0.004883]
 [0.       0.007812 0.000977]
 [0.000977 0.01563  0.      ]
 [0.       0.       0.004883]
 [0.000977 0.003906 0.000977]
 [0.       0.001953 0.      ]
 [0.       0.01367  0.000977]
 [0.004883 0.       0.01563 ]
 [0.001953 0.003906 0.000977]
 [0.006836 0.01172  0.007812]
 [0.00293  0.003906 0.00293 ]
 [0.001953 0.003906 0.      ]
 [0.009766 0.004883 0.00879 ]
 [0.00293  0.001953 0.      ]
 [0.000977 0.006836 0.001953]
 [0.00879  0.01758  0.00293 ]

In [48]:
# Exercicio 08 - Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tf.random.set_seed(42)
tensor04 = tf.random.uniform(shape=[1, 224, 224, 3])
tensor04_squeezed = tf.squeeze(tensor04)
tensor04.shape, tensor04_squeezed.shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

In [60]:
# Exercicio 09 - Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tf.random.set_seed(99)
tensor05 = tf.random.uniform(shape = [10], minval = 0, maxval = 100, dtype = tf.int32)
print(tensor05)
tf.argmax(tensor05)
tf.argmin(tensor05)

tf.Tensor([ 6 97 67 87 23 93 10  3 29 15], shape=(10,), dtype=int32)


<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [61]:
# Exercicio 10 - One-hot encode the tensor you created in 9.
tf.one_hot(tensor05, tf.size(tensor05))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>